Update install
Flipped prompt answer order to not inadvertently trick "auto yessers"

diff --git a/install b/install
--- a/install
+++ b/install
@@ -194,8 +194,8 @@ chown -R $user:$user "/home/$user" &>/tmp/srsi/srsi.logs
 # Setup server default port
 if grep -Fvq "/home/${user}/ramdisk" /etc/fstab ; then
   iptables -A INPUT -p tcp --dport 25565 -j ACCEPT
-  echo -e "${YEL}Attempt to restart networking interface?${NOR} ${RED}(This is risky business, and should not be required)${NOR}"
-  if confirm ; then
+  echo -e "${YEL}Skip restarting networking interface?${NOR} ${RED}(A restart shouldn't be required)${NOR}"
+  if ! confirm ; then
     if /etc/init.d/networking restart ; then 
       echo -e "[ ${GRE}Done${NOR} ] Networking interface restarted!\n"
     fi
